### ISSUE TITLE
Analogs error on Stampede

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#31]
I have got the following error when I try to run `AnEnV1.py` script on Stampede.

```
Starting Deallocation..
2017-07-17 14:22:39,476: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Deallocating Cluster
2017-07-17 14:22:45,081: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.stampede state has changed to Canceled
2017-07-17 14:22:45,081: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource allocation cancelled.
Resource allocation cancelled.                                              done 
geogadmins-MacBook-Air:application_AnEn wuh20$ source ~/github/ensemblemd/bin/activate
(ensemblemd) geogadmins-MacBook-Air:application_AnEn wuh20$ python AnEnV1.py xsede.stampede
2017-07-17 14:23:09,257: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
2017-07-17 14:23:09,257: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    :                      pid: 5556
2017-07-17 14:23:09,257: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    :                      tid: MainThread

================================================================================
 EnsembleMD (0.4.6)                                                             
================================================================================

Starting Allocation2017-07-17 14:23:09,907: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Requesting resources on xsede.stampede
2017-07-17 14:23:14,676: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Resource xsede.stampede state has changed to PendingLaunch
2017-07-17 14:23:14,677: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Launched 16-core pilot on xsede.stampede.
                                                           ok
Verifying pattern                                                             ok
Starting pattern execution2017-07-17 14:23:16,236: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.stampede state has changed to Launching
2017-07-17 14:23:35,131: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.stampede state has changed to PendingActive
2017-07-17 14:24:17,240: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.stampede state has changed to Active
2017-07-17 14:24:28,271: radical.entk.bag_of_tasks.static.default: MainProcess                     : Thread-3       : ERROR   : Task with ID unit.000003 failed: STDERR: Warning: Permanently added 'c557-503,129.114.90.167' (RSA) to the list of known hosts.
Resetting modules to system default

Lmod is automatically replacing "intel/15.0.2" with "gcc/4.9.1".


Due to MODULEPATH changes, the following have been reloaded:
  1) mvapich2/2.1

/work/04672/tg839717/radical.pilot.sandbox/rp.session.geogadmins-MacBook-Air.local.wuh20.017364.0001-pilot.0000/unit.000003/radical_pilot_cu_launch_script.sh: line 22: canalogs: command not found
, STDOUT:  LAST LOG: push unit to agent after ftw staging
2017-07-17 14:24:28,271: radical.entk.bag_of_tasks.static.default: MainProcess                     : Thread-3       : ERROR   : Pattern execution FAILED.
2017-07-17 14:24:28,272: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 284, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/anaconda/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 218, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], intermediate_state)
  File "/anaconda/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 87, in unit_state_cb
    sys.exit(1)
SystemExit: 1
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 339, in execute_pattern
    resource._umgr.wait_units(uids)
  File "/anaconda/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 710, in wait_units
    time.sleep (0.5)
KeyboardInterrupt

Starting Deallocation..
2017-07-17 14:24:28,417: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Deallocating Cluster
2017-07-17 14:24:30,914: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.stampede state has changed to Canceled
2017-07-17 14:24:30,914: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource allocation cancelled.
Resource allocation cancelled.                                              done
```

I have changed the `radical.pilot.sandbox` folder permission, so I think you will be able to access the folder. Let me know it doesn't work for you.

Thank you.

**Comment by mturilli** [comment]
Use Stampede as a backup resource for the experiments

**Comment by Weiming-Hu** [comment]
This `AnEnV1.py` looks pretty old now, because according to the newer version of ENTK [installation guide](http://radicalentk-06.readthedocs.io/en/arch-v0.6/install.html#installing-ensemble-toolkit), I don't need to do `pip install radical.ensemblemd`. However, `AnEnV1.py` scripts gave me the following error:
```
File "AnEnV1.py", line 5, in <module>
    from radical.ensemblemd import Kernel
```

So I went ahead and typed `pip install radical.ensemblemd`. And then I received the following error:
```
  File "AnEnV1.py", line 81, in <module>
    cluster.allocate()
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 198, in allocate
    self._session = radical.pilot.Session(database_url=self._database_url)
TypeError: __init__() got an unexpected keyword argument 'database_url'
```

Looks like some parameters have been changed. So should we still check this script? Or we probably need to move on to the newer scripts that we created together [here](https://github.com/radical-experiments/entk-experiments/tree/master/anen_base).

**Comment by vivek-bala** [comment]
Hey Weiming, I think you are running the older scripts. Our latest scripts are in https://github.com/radical-experiments/entk-experiments/blob/master/anen_base.

**Comment by Weiming-Hu** [comment]
This has been resolved.

**Comment by Weiming-Hu** [comment]
Hi team,

Unfortunately, my current class schedule conflicts with our meeting period. I have a class weekly starts at 2:30pm on Wednesday.

Is it feasible for us to start 30 minutes earlier so that the meeting is scheduled between 1:30pm to 2:30pm?

Let me know if it works for everyone. If not, I can think of other solutions. Sorry for the trouble.

Thank you
Weiming
