### ISSUE TITLE
Start new pipeline failed

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#42]
When I tried to add the iteration feature to the script, I got the following errors:

```
new session: [rp.session.geogadmins-MacBook-Air.local.wuh20.017438.0008]       \
database   : [mongodb://138.201.86.166:27017/ee_exp_4c]                       ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .                                                                     ok
True
Active pipes:  1
WFP complete:  True
Syncing task radical.entk.task.0000 with state SCHEDULING
Synced task radical.entk.task.0000 with state SCHEDULING
Syncing task radical.entk.task.0000 with state SCHEDULED
Synced task radical.entk.task.0000 with state SCHEDULED
Syncing task radical.entk.task.0001 with state SCHEDULING
Synced task radical.entk.task.0001 with state SCHEDULING
Syncing task radical.entk.task.0001 with state SCHEDULED
Synced task radical.entk.task.0001 with state SCHEDULED
State transition done
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
Syncing task radical.entk.task.0000 with state SUBMITTING
Synced task radical.entk.task.0000 with state SUBMITTING
submit 1 unit(s)
        .                                                                     ok
Syncing task radical.entk.task.0000 with state SUBMITTED
Synced task radical.entk.task.0000 with state SUBMITTED
Syncing task radical.entk.task.0001 with state SUBMITTING
Synced task radical.entk.task.0001 with state SUBMITTING
submit 1 unit(s)
        .                                                                     ok
Syncing task radical.entk.task.0001 with state SUBMITTED
Synced task radical.entk.task.0001 with state SUBMITTED
Syncing task radical.entk.task.0000 with state EXECUTED
Synced task radical.entk.task.0000 with state EXECUTED
Syncing task radical.entk.task.0000 with state DEQUEUEING
Synced task radical.entk.task.0000 with state DEQUEUEING
Syncing task radical.entk.task.0001 with state EXECUTED
Synced task radical.entk.task.0001 with state EXECUTED
Syncing task radical.entk.task.0000 with state DEQUEUED
Synced task radical.entk.task.0000 with state DEQUEUED
Syncing task radical.entk.task.0000 with state DONE
Synced task radical.entk.task.0000 with state DONE
Syncing task radical.entk.task.0001 with state DEQUEUEING
Synced task radical.entk.task.0001 with state DEQUEUEING
Syncing task radical.entk.task.0001 with state DEQUEUED
Synced task radical.entk.task.0001 with state DEQUEUED
Syncing task radical.entk.task.0001 with state DONE
Synced task radical.entk.task.0001 with state DONE
4
wait for 1 pilot(s)
                                                                              ok
closing session rp.session.geogadmins-MacBook-Air.local.wuh20.017438.0008      \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 206.4s                                                      ok
new session: [rp.session.geogadmins-MacBook-Air.local.wuh20.017438.0009]       \
database   : [mongodb://138.201.86.166:27017/ee_exp_4c]                       ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .                                                                     ok
2017-09-29 15:00:47,223: radical.saga.pty    : pmgr.launching.0                : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/Users/wuh20/virtual-python/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 290, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/Users/wuh20/virtual-python/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2017-09-29 15:00:47,228: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
^Cclosing session rp.session.geogadmins-MacBook-Air.local.wuh20.017438.0009      \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 53.6s                                                       ok
2017-09-29 15:01:26,649: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Execution interrupted by user (you probably hit Ctrl+C), trying to exit callback thread gracefully...
2017-09-29 15:01:26,650: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Execution interrupted by user (you probably hit Ctrl+C), trying to cancel enqueuer thread gracefully...
2017-09-29 15:01:26,650: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Could not cancel resource request, error: can't route 'control_pubsub' notification: {'cmd': 'cancel_pilots', 'arg': {'uids': ['pilot.0000'], 'pmgr': 'pmgr.0000'}}
Execution failed, error: can't route 'control_pubsub' notification: {'cmd': 'cancel_pilots', 'arg': {'uids': ['pilot.0000'], 'pmgr': 'pmgr.0000'}}
Traceback (most recent call last):
  File "/Users/wuh20/github/hpc-workflows/scripts/application_AnEn/anen_base/py_func_start_iteration.py", line 245, in start_iteration
    appman.run()
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 430, in run
    self._resource_manager._cancel_resource_request()
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 374, in _cancel_resource_request
    self._pilot.cancel()
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 526, in cancel
    self._pmgr.cancel_pilots(self.uid)
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 644, in cancel_pilots
    'uids' : uids}})
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1411, in publish
    raise RuntimeError("can't route '%s' notification: %s" % (pubsub, msg))
RuntimeError: can't route 'control_pubsub' notification: {'cmd': 'cancel_pilots', 'arg': {'uids': ['pilot.0000'], 'pmgr': 'pmgr.0000'}}
```

**Comment by mturilli** [comment]
Depends on #41

**Comment by Weiming-Hu** [comment]
After the discussion with Vivek, we decided on the solution that we only keep one application manager with multiple pipelines. The code has been edited.

**Comment by Weiming-Hu** [comment]
However, it seems like it is still creating multiple application managers according to the standard output.

```
(virtual-python) geogadmins-MacBook-Air:anen_base wuh20$ python script_master_new.py 
new session: [rp.session.geogadmins-MacBook-Air.local.wuh20.017444.0001]       \
database   : [mongodb://138.201.86.166:27017/ee_exp_4c]                       ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .                                                                     ok
True
Active pipes:  1
WFP complete:  True
Syncing task radical.entk.task.0000 with state SCHEDULING
Synced task radical.entk.task.0000 with state SCHEDULING
Syncing task radical.entk.task.0000 with state SCHEDULED
Synced task radical.entk.task.0000 with state SCHEDULED
Syncing task radical.entk.task.0001 with state SCHEDULING
Synced task radical.entk.task.0001 with state SCHEDULING
Syncing task radical.entk.task.0001 with state SCHEDULED
Synced task radical.entk.task.0001 with state SCHEDULED
State transition done
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
Syncing task radical.entk.task.0000 with state SUBMITTING
Synced task radical.entk.task.0000 with state SUBMITTING
submit 1 unit(s)
        .                                                                     ok
Syncing task radical.entk.task.0000 with state SUBMITTED
Synced task radical.entk.task.0000 with state SUBMITTED
Syncing task radical.entk.task.0001 with state SUBMITTING
Synced task radical.entk.task.0001 with state SUBMITTING
submit 1 unit(s)
        .                                                                     ok
Syncing task radical.entk.task.0001 with state SUBMITTED
Synced task radical.entk.task.0001 with state SUBMITTED
Syncing task radical.entk.task.0001 with state EXECUTED
Synced task radical.entk.task.0001 with state EXECUTED
Syncing task radical.entk.task.0001 with state DEQUEUEING
Synced task radical.entk.task.0001 with state DEQUEUEING
Syncing task radical.entk.task.0001 with state DEQUEUED
Synced task radical.entk.task.0001 with state DEQUEUED
Syncing task radical.entk.task.0001 with state DONE
Synced task radical.entk.task.0001 with state DONE
Syncing task radical.entk.task.0000 with state EXECUTED
Synced task radical.entk.task.0000 with state EXECUTED
Syncing task radical.entk.task.0000 with state DEQUEUEING
Synced task radical.entk.task.0000 with state DEQUEUEING
Syncing task radical.entk.task.0000 with state DEQUEUED
Synced task radical.entk.task.0000 with state DEQUEUED
Syncing task radical.entk.task.0000 with state DONE
Synced task radical.entk.task.0000 with state DONE
4
2017-10-05 10:56:11,078: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread: 
Traceback (most recent call last):
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 320, in _enqueue
    mq_connection.close()
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 688, in close
    self._flush_output(self._closed_result.is_ready)
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 440, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 338, in _enqueue
    raise Error(text=ex)
Error: Error: 

wait for 1 pilot(s)
                                                                              ok
closing session rp.session.geogadmins-MacBook-Air.local.wuh20.017444.0001      \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 320.4s                                                      ok
new session: [rp.session.geogadmins-MacBook-Air.local.wuh20.017444.0002]       \
database   : [mongodb://138.201.86.166:27017/ee_exp_4c]                       ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .                                                                     ok
2017-10-05 10:56:31,576: radical.saga.pty    : pmgr.launching.0                : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/Users/wuh20/virtual-python/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 290, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/Users/wuh20/virtual-python/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2017-10-05 10:56:31,706: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
```

**Comment by Weiming-Hu** [comment]
This has been resolved in the script_master_Weiming.py
