### ISSUE TITLE
Error on Cheyenne

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-collaboration/hpc-workflows#65]
Hi there,

I've followed the document installation and tried to set up the enviroment on NCAR Cheyenne. I've set up the system environment `RADICAL_PILOT_DBURL`, `RMQ_HOSTNAME`, and `RMQ_PORT`.

When I'm trying to run the simple example `eop.py` I had the following error messages.

```
(env-entk) wuh20@cheyenne6:~/virtual-envs/env-entk/share/radical.entk/simple_examples/scripts> RADICAL_ENTK_VERBOSE=INFO python eop.py
2018-09-26 11:20:48,150: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 (default, Jan 28 2018, 18:16:26) [GCC Intel(R) C++ 
gcc 4.8 mode]
2018-09-26 11:20:48,151: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 42817/MainThread
2018-09-26 11:20:48,151: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Application Manager initialized
2018-09-26 11:20:48,264: radical.entk.task_processor: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 (default, Jan 28 2018, 18:16:26) [GCC Intel(R) C++ $
cc 4.8 mode]
2018-09-26 11:20:48,264: radical.entk.task_processor: MainProcess                     : MainThread     : INFO    :                      pid/tid: 42817/MainThread
2018-09-26 11:20:48,265: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 (default, Jan 28 2018, 18:16:26) [GCC Intel($
) C++ gcc 4.8 mode]
2018-09-26 11:20:48,266: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 42817/MainThread
2018-09-26 11:20:48,266: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Created resource manager object: resource_manager.0000
2018-09-26 11:20:48,266: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource description validated
2018-09-26 11:20:48,266: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Workflow assigned to Application Manager
2018-09-26 11:20:50,629: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.14 (default, Jan 28 2018, 18:16:26) [GCC Intel(R) C+$
 gcc 4.8 mode]
2018-09-26 11:20:50,629: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 42817/MainThread
2018-09-26 11:20:50,629: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : Created WFProcessor object: wfprocessor.0000
2018-09-26 11:20:50,639: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting resource request submission
2018-09-26 11:20:51,012: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-09-26 11:20:51,012: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager: 'Logger' object has no attribute 'report'
Traceback (most recent call last):
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 310, in run
    self._resource_manager._submit_resource_request()
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 126, in _submit_resource_request
    self._session = rp.Session(dburl=self._mlab_url, uid=self._sid)
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/pilot/session.py", line 259, in __init__
    self._log.report.error(">>err\n")
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/utils/logger.py", line 352, in __getattr__
    return getattr(self._logger, attr)
AttributeError: 'Logger' object has no attribute 'report'
2018-09-26 11:20:51,013: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
Traceback (most recent call last):
  File "eop.py", line 103, in <module>
    appman.run()
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 310, in run
    self._resource_manager._submit_resource_request()
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 126, in _submit_resource_request
    self._session = rp.Session(dburl=self._mlab_url, uid=self._sid)
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/pilot/session.py", line 259, in __init__
    self._log.report.error(">>err\n")
  File "/gpfs/u/home/wuh20/virtual-envs/env-entk/lib/python2.7/site-packages/radical/utils/logger.py", line 352, in __getattr__
    return getattr(self._logger, attr)
AttributeError: 'Logger' object has no attribute 'report'
```

This is my environment settings.

```
(env-entk) wuh20@cheyenne6:~/virtual-envs/env-entk/share/radical.entk/simple_examples/scripts> radical-stack

  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /gpfs/u/home/wuh20/virtual-envs/env-entk

  radical.entk         : 0.7.6
  radical.pilot        : 0.47-0.47-20-gb840c12@feature-cheyenne
  radical.utils        : 0.50.1-v0.50.1-3-g2b7f6c6@devel
  saga                 : 0.47.3-merge-pre_gpu-36-g74bd841@feature-cheyenne
```

Thank you.

**Comment by vivek-bala** [comment]
Hey @andre-merzky , this seems like a mismatch between the different versions. Can you advise on which utils version to use? I don't remember the one that I had used previously.

or maybe RP/SAGA branches need to be updated as well. Probably that is on a longer time scale.

**Comment by vivek-bala** [comment]
Short term could be to get the specific branch or version of radical utils. Long term we will have to merge the cheyenne branches into master/release.

**Comment by Weiming-Hu** [comment]
Hi there. A quick update. A [toy test](https://github.com/radical-collaboration/hpc-workflows/blob/master/scripts/application_AnEn/year_2/test.py) is passed on Wrangler.

**Comment by vivek-bala** [comment]
We have fixed the issues in SAGA and RP. The devel branch of both have been tested on Cheyenne to be successful.

**Comment by andre-merzky** [comment]
Great - I am going to merge and release the branches.  Thanks!
